<?php

/**
 * Stories - Demo-Daten fuer Channel-ContentBox - rl2014
 */

$row_stories = array(
	array(
		'href' => '#',
		'image' => '/site/img/620x250/2.jpg',
		'alt' => 'Ronaldo schießt Ibrahimowic raus',
		'copyright' => 'Getty Images',
		'tagging' => 'Drei neue Handys',
		'caption' => 'Ronaldo schießt Ibrahimowic raus (ygpq)',
		'text' => 'In Lissabon entschied Ronaldo das erste Duell der Superstars gegen Zlatan Ibrahimovic für sich.',
	),
	array(
		'href' => '#',
		'image' => '/site/img/294x147/2.jpg',
		'alt' => 'Nokia startet günstige Android-Smartphones',
		'copyright' => 'Getty Images',
		'tagging' => 'Drei neue Handys',
		'caption' => 'Nokia startet günstige Android-Smartphones',
		'text' => 'Neue Produktfamilie "Nokia X" setzt auf das Google-Betriebssystem. Neue Produktfamilie "Nokia X" setzt auf das Google-Betriebssystem.',
	),
	array(
		'href' => '#',
		'image' => '/site/img/294x147/1.jpg',
		'alt' => 'Österreichern ist das iPhone zu teuer',
		'copyright' => 'Getty Images',
		'tagging' => 'Weg vom Premium-Handy',
		'caption' => 'Österreichern ist das iPhone zu teuer',
		'text' => 'Mittelklasse-Smartphones um 350 Euro sind hierzulande voll im Trend.'
	),
	array(
		'href' => '#',
		'image' => '/site/img/294x147/3.jpg',
		'alt' => 'Aufkleben und gewinnen',
		'copyright' => 'Getty Images',
		'tagging' => 'Anzeige',
		'caption' => 'Aufkleben und gewinnen',
		'text' => 'Jetzt Flugblatt-Sticker auf Ihren Briefkasten kleben und tolle Preise gewinnen!',
	),
	array(
		'href' => '#',
		'image' => '/site/img/294x147/4.jpg',
		'alt' => 'Faschingsumzug: Frauen sexuell belästigt',
		'copyright' => 'Getty Images',
		'tagging' => 'Tirol',
		'caption' => 'Faschingsumzug: Frauen sexuell belästigt',
		'text' => 'Opfer mussten sich laut Polizei bis auf die Unterwäsche ausziehen.',
	),
	array(
		'href' => '#',
		'image' => '/site/img/620x250/2.jpg',
		'alt' => 'Ronaldo schießt Ibrahimowic raus',
		'copyright' => 'Getty Images',
		'tagging' => 'Drei neue Handys',
		'caption' => 'Ronaldo schießt Ibrahimowic raus (ygpq)',
		'text' => 'In Lissabon entschied Ronaldo das erste Duell der Superstars gegen Zlatan Ibrahimovic für sich.',
	),
	array(
		'href' => '#',
		'image' => '/site/img/294x147/2.jpg',
		'alt' => 'Nokia startet günstige Android-Smartphones',
		'copyright' => 'Getty Images',
		'tagging' => 'Drei neue Handys',
		'caption' => 'Nokia startet günstige Android-Smartphones',
		'text' => 'Neue Produktfamilie "Nokia X" setzt auf das Google-Betriebssystem. Neue Produktfamilie "Nokia X" setzt auf das Google-Betriebssystem.',
	),
	array(
		'href' => '#',
		'image' => '/site/img/294x147/1.jpg',
		'alt' => 'Österreichern ist das iPhone zu teuer',
		'copyright' => 'Getty Images',
		'tagging' => 'Weg vom Premium-Handy',
		'caption' => 'Österreichern ist das iPhone zu teuer',
		'text' => 'Mittelklasse-Smartphones um 350 Euro sind hierzulande voll im Trend.'
	),
	array(
		'href' => '#',
		'image' => '/site/img/294x147/3.jpg',
		'alt' => 'Aufkleben und gewinnen',
		'copyright' => 'Getty Images',
		'tagging' => 'Anzeige',
		'caption' => 'Aufkleben und gewinnen',
		'text' => 'Jetzt Flugblatt-Sticker auf Ihren Briefkasten kleben und tolle Preise gewinnen!',
	),
	array(
		'href' => '#',
		'image' => '/site/img/294x147/4.jpg',
		'alt' => 'Faschingsumzug: Frauen sexuell belästigt',
		'copyright' => 'Getty Images',
		'tagging' => 'Tirol',
		'caption' => 'Faschingsumzug: Frauen sexuell belästigt',
		'text' => 'Opfer mussten sich laut Polizei bis auf die Unterwäsche ausziehen.',
	),
	array(
		'href' => '#',
		'image' => '/site/img/620x250/2.jpg',
		'alt' => 'Ronaldo schießt Ibrahimowic raus',
		'copyright' => 'Getty Images',
		'tagging' => 'Drei neue Handys',
		'caption' => 'Ronaldo schießt Ibrahimowic raus (ygpq)',
		'text' => 'In Lissabon entschied Ronaldo das erste Duell der Superstars gegen Zlatan Ibrahimovic für sich.',
	),
	array(
		'href' => '#',
		'image' => '/site/img/294x147/2.jpg',
		'alt' => 'Nokia startet günstige Android-Smartphones',
		'copyright' => 'Getty Images',
		'tagging' => 'Drei neue Handys',
		'caption' => 'Nokia startet günstige Android-Smartphones',
		'text' => 'Neue Produktfamilie "Nokia X" setzt auf das Google-Betriebssystem. Neue Produktfamilie "Nokia X" setzt auf das Google-Betriebssystem.',
	),
	array(
		'href' => '#',
		'image' => '/site/img/294x147/1.jpg',
		'alt' => 'Österreichern ist das iPhone zu teuer',
		'copyright' => 'Getty Images',
		'tagging' => 'Weg vom Premium-Handy',
		'caption' => 'Österreichern ist das iPhone zu teuer',
		'text' => 'Mittelklasse-Smartphones um 350 Euro sind hierzulande voll im Trend.'
	),
	array(
		'href' => '#',
		'image' => '/site/img/294x147/3.jpg',
		'alt' => 'Aufkleben und gewinnen',
		'copyright' => 'Getty Images',
		'tagging' => 'Anzeige',
		'caption' => 'Aufkleben und gewinnen',
		'text' => 'Jetzt Flugblatt-Sticker auf Ihren Briefkasten kleben und tolle Preise gewinnen!',
	),
	array(
		'href' => '#',
		'image' => '/site/img/294x147/4.jpg',
		'alt' => 'Faschingsumzug: Frauen sexuell belästigt',
		'copyright' => 'Getty Images',
		'tagging' => 'Tirol',
		'caption' => 'Faschingsumzug: Frauen sexuell belästigt',
		'text' => 'Opfer mussten sich laut Polizei bis auf die Unterwäsche ausziehen.',
	),
);
